CREATE TABLE PRODUCTOS (CODIGOARTICULO VARCHAR(4), SECCION VARCHAR(11), NOMBREARTICULO VARCHAR(20));

INSERT INTO PRODUCTOS (CODIGOARTICULO, SECCION, NOMBREARTICULO)
VALUES
("AR01", "DEPORTES", "RAQUETA"),
("AR02", "FERRETERIA", "CHINCHETA");